version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=${MONGO_URI}
      - API_KEY=${API_KEY}
      - SHOW_DEBUG=${SHOW_DEBUG:false}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3